#define SFX_KNOCK          0
#define SFX_DOOROPEN       1
#define SFX_CHEST          2
#define SFX_SEARCH         3
#define SFX_BUY            4
#define SFX_SWORD          5
#define SFX_MENUOPEN       6
#define SFX_MENUCURSOR     7
#define SFX_MENUACCEPT     7
#define SFX_MENUCANCEL     9
#define SFX_MENUERROR      10
#define SFX_ARROWSHOT      11
#define SFX_ARROWHIT       12
#define SFX_ESCAPE         13
#define SFX_CLAW           14
#define SFX_GOLEM          15
#define SFX_THROW          16
#define SFX_LAND           17
#define SFX_FALL           18
#define SFX_ENGULF         19
#define SFX_ENGULFFLAME    20
#define SFX_TIDAL          21
#define SFX_POOF           22
#define SFX_STAFF          23
#define SFX_LEAP           24
#define SFX_CURE           25
#define SFX_SPARKLE        26
#define SFX_REVIVE         27
#define SFX_SOULSLURP      28
#define SFX_SACRIFICE      29
#define SFX_STARTBATTLE    30
#define SFX_ENEMYCAST      31
#define SFX_LIGHTNING      32
#define SFX_CHARM          33
#define SFX_SPAWN          34
#define SFX_GEM            35
#define SFX_LEVELUP        36
#define SFX_TOWERRAISE     37
#define SFX_QUAKEFADE      38
#define SFX_CANNONFIRE     39
#define SFX_NIGHTTIME      40
#define SFX_WAVES1         41
#define SFX_WAVES2         42
#define SFX_WAVES3         43
#define SFX_RESETSOUND     44
#define SFX_INVERSION      45
#define SFX_JUSTICE        46
#define SFX_ROAR           47
#define SFX_WHIRLWIND      48
#define SFX_WATERLEVEL     49
#define SFX_WARP           50
#define SFX_ROCKGRIND      51
#define SFX_ROLANDSWORD    52
#define SFX_ICEBREAK       53
#define SFX_PORTALOPEN     54
#define SFX_CRITICAL       55
#define SFX_SPLASH         56

#define SFX_HOPE SFX_SPARKLE

#define SNG_TITLE       0
#define SNG_PROPHECY    1
#define SNG_OVERWORLD   2
#define SNG_TOWN1       3
#define SNG_CASTLE      4
#define SNG_MOUNTAIN    5
#define SNG_FIGHT1      6
#define SNG_BOSS1       7
#define SNG_REST        8
#define SNG_GAMEOVER    9
#define SNG_CAVE1       10
#define SNG_CREATOR     11
#define SNG_CREATOREVIL 12
#define SNG_TOWN2       13
#define SNG_KASSIM      14
#define SNG_FOREST      15
#define SNG_ALUTHA      16
#define SNG_MYSTERY     17
#define SNG_TROUBLE     18
#define SNG_VICTORY     19
#define SNG_SADNESS     20
#define SNG_SAILING     21
#define SNG_ICECAVERN   22
#define SNG_MYSTIC      23
#define SNG_GREATDARK   24
#define SNG_LASTBOSS    25
#define SNG_ENDING1     26
#define SNG_ENDING2     27
#define SNG_NIGHTTIME   28
